-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.blogs
(
    blog_id integer NOT NULL DEFAULT nextval('blogs_blog_id_seq'::regclass),
    title character varying(255) COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default",
    type character varying(10) COLLATE pg_catalog."default",
    user_id integer,
    currency_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT blogs_pkey PRIMARY KEY (blog_id)
);

CREATE TABLE IF NOT EXISTS public.cryptocurrencies
(
    currency_id integer NOT NULL DEFAULT nextval('cryptocurrencies_currency_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default",
    symbol character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT cryptocurrencies_pkey PRIMARY KEY (currency_id)
);

CREATE TABLE IF NOT EXISTS public.exchange_rates
(
    exchange_rates_id integer NOT NULL DEFAULT nextval('exchange_rates_exchange_rates_id_seq'::regclass),
    from_currency_id integer,
    to_currency_id integer,
    exchange_rate numeric(10, 5),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT exchange_rates_pkey PRIMARY KEY (exchange_rates_id),
    CONSTRAINT unique_from_to_currency UNIQUE (from_currency_id, to_currency_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL DEFAULT nextval('users_user_id_seq'::regclass),
    username character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    role character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.wallet
(
    wallet_id integer NOT NULL DEFAULT nextval('wallet_wallet_id_seq'::regclass),
    user_id integer,
    currency_id integer,
    balance numeric(10, 2),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT wallet_pkey PRIMARY KEY (wallet_id)
);

ALTER TABLE IF EXISTS public.blogs
    ADD CONSTRAINT blogs_currency_id_fkey FOREIGN KEY (currency_id)
    REFERENCES public.cryptocurrencies (currency_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.blogs
    ADD CONSTRAINT blogs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.exchange_rates
    ADD CONSTRAINT exchange_rates_from_currency_id_fkey FOREIGN KEY (from_currency_id)
    REFERENCES public.cryptocurrencies (currency_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.exchange_rates
    ADD CONSTRAINT exchange_rates_to_currency_id_fkey FOREIGN KEY (to_currency_id)
    REFERENCES public.cryptocurrencies (currency_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallet
    ADD CONSTRAINT wallet_currency_id_fkey FOREIGN KEY (currency_id)
    REFERENCES public.cryptocurrencies (currency_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wallet
    ADD CONSTRAINT wallet_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

    ALTER TABLE public.wallet
ADD COLUMN transaction_type VARCHAR(10);


END;